### PR TITLE
Enable windows for travis

### PR DESCRIPTION
**Pull request by cemremengu**
Enable windows testing to verify that file generation is cross platform. Hopefully tests cover this though.

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina tests fail. Possible root cause for `fastify-cli`

**Comment by mcollina** [comment]
Would you like to amend this to fix them?

**Comment by cemremengu** [comment]
Sure, will look into it.

**Review by mcollina — APPROVED** [review]
LGTM

**Pull request merged**
